apiVersion: kctf.dev/v1
kind: Challenge
metadata:
  name: xml-translator
spec:
  deployed: true
  powDifficultySeconds: 0
  network:
    public: true
    ports:
      - protocol: "HTTPS"
        targetPort: 80
        domains:
          - "challs2.infobahnc.tf"
  healthcheck:
    enabled: false
  podTemplate:
    template:
      spec:
        containers:
          - name: challenge
            env:
            securityContext:
              readOnlyRootFilesystem: false
